version: '3.4'

services:
  piestimatorbackend:
    image: piestimatorbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./.env

  db:
    image: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: points
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/data
    ports:
      - 5432:5432

volumes:
  db-data:

